<?php $this->partial("shared/header"); ?>

    <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->


    <div  style="margin:0px auto;max-width:600px;">

        <table
                align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"
        >
            <tbody>
            <tr>
                <td
                        style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;"
                >
                    <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->

                    <div
                            class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
                    >

                        <table
                                border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
                        >
                            <tbody>

                            <tr>
                                <td
                                        align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                                >

                                    <div
                                            style="font-family:Nunito, Roboto, Helvetica, Arial, sans serif;font-size:32px;font-weight:700;line-height:28px;text-align:center;color:#FFFFFF;"
                                    >Hi, <?php echo $username ?> welcome to DevBook !</div>

                                </td>
                            </tr>

                            <tr>
                                <td
                                        align="center" style="font-size:0px;padding:10px 25px;padding-top:15px;padding-bottom:35px;word-break:break-word;"
                                >

                                    <table
                                            border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
                                    >
                                        <tbody>
                                        <tr>
                                            <td  style="width:400px;">

                                                <img
                                                        alt="Book" height="auto" src="https://i.postimg.cc/Jn04QMkr/Rectangle.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="400"
                                                />

                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>

                                </td>
                            </tr>

                            <tr>
                                <td
                                        align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                                >

                                    <div
                                            style="font-family:Nunito, Roboto, Helvetica, Arial, sans serif;font-size:16px;line-height:20px;text-align:center;color:#FFFFFF;"
                                    >Your account was created on DevBook. To verify your e-mail address, click on the button bellow.</div>

                                </td>
                            </tr>

                            <tr>
                                <td
                                        align="center" vertical-align="middle" style="font-size:0px;padding:10px 25px;padding-top:20px;padding-bottom:20px;word-break:break-word;"
                                >

                                    <table
                                            border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
                                    >
                                        <tbody>
                                        <tr>
                                            <td
                                                    align="center" bgcolor="#FF9F1C" role="presentation" style="border:none;border-radius:4px;cursor:auto;mso-padding-alt:10px 25px;background:#FF9F1C;" valign="middle"
                                            >
                                                <a
                                                        href="<?php echo $publicUrl . $confirmUrl ?>" style="display:inline-block;background:#FF9F1C;color:#ffffff;font-family:Nunito, Roboto, Helvetica, Arial, sans serif;font-size:16px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:4px;" target="_blank"
                                                >
                                                    Confirm my e-mail
                                                </a>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>

                                </td>
                            </tr>

                            </tbody>
                        </table>

                    </div>

                    <!--[if mso | IE]></td></tr></table><![endif]-->
                </td>
            </tr>
            </tbody>
        </table>

    </div>


    <!--[if mso | IE]></td></tr></table><![endif]-->


<?php $this->partial("shared/footer"); ?>